version: "3"
services:  
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    ports:
      - "8388:8388/tcp"
      - "8388:8388/udp"
    environment:
      - METHOD=chacha20-ietf-poly1305
      - PASSWORD=${PASSWORD}
    restart: always
